### ISSUE TITLE
Macros from Fluidd don't work

### ISSUE THREAD

**Issue by flauta** [mairyj/Elegoo-Neptune-4-Series#10]
Printer: Neptune 4 with Wifi network (your Cura profile & settings) 
Browser: Chromium & Firefox

I'm sorry maybe I don't understand how macros work, but I can't see any of them working.
The command appears in the 'command line' window of Fluidd, but the printer does not change any setting.
The only command that has a reaction from the command line is "All lights" - command line transcript follows.

------------------------------------------------------------
$ all_lights
// Running Command {FLASHLIGHT}...:
// sh: 0: Can't open /home/mks/sled2.sh
// Command {FLASHLIGHT} finished
// Running Command {MODLELIGHT}...:
// sh: 0: Can't open /home/mks/sled1.sh
// Command {MODLELIGHT} finished

**Comment by mairyj** [comment]
Hello can you tell me what version and what machine I will check. Did you
do the last update?

**Comment by flauta** [comment]
Thanks for the reply and for your work.
Yes I did all the updates. Both of your printer.cfg (dated 2024-02-13) and of printer firmware (1.1.2.53)

**Comment by mairyj** [comment]
For the Neptune 4 or Neptune 4 pro?

**Comment by flauta** [comment]
Neptune 4 as I wrote

**Comment by mairyj** [comment]
Hello so it will depend on whether you have a V1 or V2 motherboard.
In my last printer.cfg I put the commands for the 2 versions so yes certain
commands will not work.

For V1 the macros are:
MODLELIGHT_ON/OFF
FLASHLIGHT_ON/OFF

for V2:
FLASHLIGHT_SWITCH
MODLELIGHT_SWITCH
ALL_LIGHTS

It should work in one of the two cases where you do not have the latest
update.

**Comment by flauta** [comment]
Sorry I don't know where to read this motherboard version number. 
My printer has the serial # NEP4.23921.A0273
I installed your config because I decided to trust you and your knowledge of the printer. The light macros aren't so important after all. Or should I get back to the previous update? Are there other (more important) settings that don't work?

Thanks

**Comment by mairyj** [comment]
as I indicated to you, regardless of the version of the card, I have
integrated all the macros but some will work for v1 and others for v2.

**Comment by flauta** [comment]
I added manually via ssh the two bash scripts to the mks home directory - now the light macros work.
Thanks again for your work.
