### ISSUE TITLE
Installation timelapse

### ISSUE THREAD

**Issue by flc85** [mairyj/Elegoo-Neptune-4-Series#11]
attention avec la commande suivante à bien laisser un espace entre les 2 parties (cad entre timelapse.cfg et /home 
`sudo ln -s /home/mks/moonraker-timelapse/klipper_macro/timelapse.cfg /home/mks/klipper_config/timelapse.cfg`

**Comment by mairyj** [comment]
bonjour merci pour la remarque pas évident à mettre en page sur le tuto
