### ISSUE TITLE
Question concernant le PRINTER.CFG

### ISSUE THREAD

**Issue by ygarand** [mairyj/Elegoo-Neptune-4-Series#2]
Bonjour,

J'ai suivi tout tes vidéos de ta chaîne YouTube et merci beaucoup.  Je me demandais si je met à jour le printer.CFG avec la nouvelle version.  Est-ce que je dois tout refaire les tutos comme (bed leveling, PID, Extruder, etc) ou je peux prendre certain donnée et les recopier ?

Merci

**Comment by mairyj** [comment]
Bonjour, alors oui c'est possible de reprendre les données que tu as. En
fait, toutes les parties SAVE CONFIG en bas du printer.cfg sont les données
qui ont changé.
Je prépare un tuto afin de montrer comment faire ^^
