### ISSUE TITLE
Timelaspse

### ISSUE THREAD

**Issue by peebee** [mairyj/Elegoo-Neptune-4-Series#4]
Bonjour, 
Depuis la dernière version le processus d'installation du timelapse ne semble plus fonctionnel (Je n'avais pas testé avant) 
J'au dû passer par l'installateur de Moonraker, que j'ai trouvé [ICI  ](https://github.com/mainsail-crew/moonraker-timelapse/blob/main/docs/installation.md)
Merci pour ce site 

Imprimante Nep4 pro 
version firmware 1.1.2.53

**Comment by mairyj** [comment]
Bonjour merci pour votre retour effectivement vous n'êtes pas le premier a me le dire je dois vérifier pourtant les commandes sont identique. je vais peaufiner le tuto pendant les vacances ;-)
