### ISSUE TITLE
Printer.cfg

### ISSUE THREAD

**Issue by peebee** [mairyj/Elegoo-Neptune-4-Series#5]
Bonjour,

Je viens de mettre en œuvre un ADXL via USB sur ma Neptune 4 Pro, je dois dire que j'ai bien galéré, en la flachant et le reflachant en Rampon ou ADXL mais rien n'y faisait.

Avec de m'apercevoir que le fichier printer.cfg contenait déjà des paramètres pour ADXL.
En les commentant, tout a normalement fonctionné ;-) 

Pourrais tu ajouté un commentaire dans le fichier printer.cfg et ajouté ADXL dans ton Menu 
Attention la configuration existante est celle de l'ADXL branché sur le port SPI existant sur les cartes mère de la 4 et 4 Pro.

Merci 
PS j'ai regardé la conf d'origine, ces paramètres existent déjà

**Comment by mairyj** [comment]
Bonjour merci pour la remarque il est vrai que je peux commenter la partie
config ADXL et laisser juste input shaper ;-) je fais cela tout de suite.
Que voulez-vous dire par "ajouté ADXL dans ton menu"?

D'avance merci

Julien

Le sam. 6 janv. 2024 à 14:37, Bousquet Pascal ***@***.***> a
écrit :

**Comment by peebee** [comment]
Oui pardon pas menu mais index, c'est tellement pratique

**Comment by peebee** [comment]
Je t'envoie mon petit retour sur l'installation de ADXL par mail, tu peux l'ajouter dans ton Github si tu le souhaites 
J'en profite pour me répondre aussi sur le Groupe Facebook au ca ou une personne galère comme moi :-)

**Comment by mairyj** [comment]
Ah oui ok pour que cela soit plus clair a trouvé, je vais faire cela aussi

Le sam. 6 janv. 2024 à 15:01, Bousquet Pascal ***@***.***> a
écrit :

**Comment by mairyj** [comment]
Voilà index modifier ;-) il est vrai que je pourrais ajouter le fichier
pour les ADXL mais cela va dépendre du modèle.
