### ISSUE TITLE
My printer.cfg

### ISSUE THREAD

**Issue by ZSpidla** [mairyj/Elegoo-Neptune-4-Series#8]
Hi,

for the first many thanks for your content.
Regarding: Elegoo-Neptune-4-Series-main\Neptune 4 Pro\My printer.cfg\Stepping Motor BJ42D22-53V04\Base 1.1.2.53\printer.cfg

[input_shaper]
shaper_freq_x: 66.66    #68.4
shaper_freq_y: 42.05    #45.6
shaper_type_x: mzv
shaper_type_y: ei

But in the [gcode_macro PRINT_START] is a command SET_INPUT_SHAPER SHAPER_TYPE=ei  which caused  both x/y axes are controlled by ei shaper ( frequiences remain X:66.66 and Y42.05). Which is reported in console window after print start.

Q1: What is the reason for  using SET_INPUT_SHAPER SHAPER_TYPE=ei ?

Thanks

Regards Zdenek

**Comment by mairyj** [comment]
Hello, thank you for this remark, it's elegoo's print_start and I hadn't
paid attention. I will check and change this right away on all versions.
Thank you very much for the remark.

**Comment by mairyj** [comment]
The correction has been applied to all versions, thank you very much for this very relevant remark.

**Comment by ZSpidla** [comment]
You're welcome. It is my pleasure to use your config on my N4P. Zdenek
