### ISSUE TITLE
Probleme test file elegoo neptune 4 plus

### ISSUE THREAD

**Issue by montana8134** [mairyj/Elegoo-Neptune-4-Series#9]
Bonjour et d’abord merci pour votre travail .
J'ai un soucis quand je veux transférer  les fichiers test gcode de cura à mon imprimante et quelque soit le fichier j'ai l'erreur list index out of range qui s'affiche j'ai pourtant paramétré cura avec votre tuto.
Si vous avez une idée je suis preneur ;)
Et encore merci pour vos videos qui m'ont vraiment aidés a paramétrer ma nouvelle imprimante

**Comment by mairyj** [comment]
Bonjour que voulez-vous dire par transférer les fichiers test?
une fois slicer vous voulez les envoyer directement vers l'imprimante via
votre réseau?

Le mar. 13 févr. 2024 à 16:29, montana8134 ***@***.***> a
écrit :

**Comment by montana8134** [comment]
Oui c'est au moment d'envoyer directement vers l'imprimante via reseau

**Comment by montana8134** [comment]
Bon au final en passant par une cle usb tout fonctionne 😀

**Comment by mairyj** [comment]
Bonjour si vous n'arriver pas a envoyer depuis cura c'est que le plugin
moonraker n'a pas été correctement configuré ;-)

Le dim. 18 févr. 2024 à 17:04, montana8134 ***@***.***> a
écrit :
